<a href="https://colab.research.google.com/github/Skywalk-dev/tensorflow-developer-certificate/blob/main/01_tensorflow_fundamentals/01_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this we are going through some of the most fundamental concept of tensars using tensarflow.

# Introduction to tensors


More speecifically we are going to cover
* Introductions to tensors
* Getting informations from tensors
* Manupulating Tensors
* Tensors and Numpy
* Using @tf.function(a way to speed up your python function)
* Using GPU/TPU with Tensarflow
* Excercises to try

In [ ]:
#Import tensarFlow
import tensorflow as tf
print(tf.__version__)

2.20.0


In [ ]:
# Create tensars with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimentions of the tensor (ndim stands for number of dimentions)

scalar.ndim


0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimention of the vector
vector.ndim

1

In [ ]:
# create a matrix ( matrix has more than one dimention)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.8,7.6,3],
                              [12.5,3,6],
                              [3,6.8,1]], dtype = tf.float16 ) # specify the datatype with dtype parameter
another_matrix


<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.8,  7.6,  3. ],
       [12.5,  3. ,  6. ],
       [ 3. ,  6.8,  1. ]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Lets create a tensar
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim


3

What we have created so far:

* Scalar: a single number
* vector: a number with dimention(e.g. wind speed and direction)
* MAtrix: a 2-dimentional array of numbers
* Tensors: a n-dimentional array of numbers(where n can be any number, a 0-dimention tensor is a scalar, a 1-dimentional tensor is a vector)

### Creating tensors with tf.variable

In [ ]:
# Create the same tensors with tf.variable() as above

change_tensor = tf.Variable([10,7])
unchange_tensor = tf.constant([10,7])
print (change_tensor)
print (unchange_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [ ]:
# Lets change one of the element of changable tensors

change_tensor [0] = 7


TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Lets change one of the element with .assign operator
change_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Lets try with one of the unchange tensor
unchange_tensor[0].assign(7)
unchange_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Note: Rarely in practice we will need to decide weather to use tf.constant or tf.Variable to create tensors as the tensorFlow does it for yoursef.
However if in doubt, use tf.constant and change it later if needed.

Creating random tensors :
Random tensors are some tensors with arbitory size and witch contains random numbers

In [ ]:
# lets create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(10) # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(10)
random_2 = random_2.normal(shape = (3,2))
random_1 , random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffel the order of element in a tensor

In [ ]:
# Shuffel the tensor (valuable for when you want to shuffle the data so the inherent dosnot effect learning)
not_shuffled = tf.constant([[10,7],
                           [8,9],
                           [2,5]])


#How to shuffel our non suffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  9],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
shuffle_1 = tf.constant([[9,10,11],[12,13,14],[15,16,17]])
tf.random.shuffle(shuffle_1,seed = 42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11]], dtype=int32)>

In [ ]:
shuffle_2 = tf.constant([[1,2,3],[4,5,9],[9,8,7]])
tf.random.set_seed(42)
shuffle_2.ndim

2

In [ ]:
shuffle_3 = tf.constant([[9,10,12],[26,27,28],[37,38,39]])
tf.random.shuffle(shuffle_3)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 10, 12],
       [37, 38, 39],
       [26, 27, 28]], dtype=int32)>

## Other ways to make tensors




In [ ]:
## Create a tensor of all ones

tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
##Create a tensor of all zeros
tf.zeros(shape = (4,7))

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

Turn Numpy arrays into tensors

The main difference between numpy arrays and tensors in tensor flow is that tensors and be run on GPU's and its much faster for numerical computing

20 video study 3 times
hw

In [ ]:
## you can also turn Numpy into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # creates a numpy array between 1 and 15)
numpy_A

# X = tf.constant(for some_matrix)# capital for matrix or tensor
# y = tf.constant(vector) # non capital for vctors


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape=(3,8))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

Getting information from tensors

When deeling with tensors you should be aware of the following atributes:

* Shape -> The length (number of elements) of each of the dimentions of a  tensor code tensor.shape
* Rank -> The number of tensor dimentions.A scalar has rank 0, a vector has rank1, a matrix has rank 2, a tensor has rank n. code tensor.ndim
* Actions or dimentions -> A perticular dimention of a tensor. tensor[0],tensor[:,1]
* Size -> the total number of items in the tensor code tf.size(tensor)


In [ ]:
## Create rank 4 tensors(4 dimention)

rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
## get variable attributes of our tensors (print statements)

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimentions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensors:",tf.size(rank_4_tensor))
print("Total number of elements in our tensors:",tf.size(rank_4_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
Number of dimentions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensors: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensors: 120


Indexing tensors
* Tensor can be indexed just like python lists

In [ ]:
# python lists

some_list = [4,5,6,7]
some_list[:1]

[4]

In [ ]:
## Get first two elements of each dimentions
rank_4_tensor[:2,:2,:2,:2]





<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimention from each index except from the final one

rank_4_tensor[:1,:1,:1,:]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimention)
rank_2_tensor = tf.constant([[10,7],
                             [7,10]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# python list looks like

some_list, some_list[-1]

([4, 5, 6, 7], 7)

In [ ]:
# Get the last item of each of row of rank 2 tensors

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
## Add in extra dimention to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [ ]:
## Alternative for tf.newaxis

tf.expand_dims(rank_2_tensor, axis= -1) # '-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [ ]:
# practice
rank_4_tensor[...,-1]

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
List = [1,2,3,4,5]
List[:4]

[1, 2, 3, 4]

In [ ]:
# we want to get the first elemet of each dimention from each index except for the final one

rank_4_tensor[:,:1,:1,:1]
rank_4_tensor.shape
rank_4_tensor[...,tf.newaxis]



TensorShape([2, 3, 4, 5])

Manupulating tensors(tensor operations)

** Basic operations**
`+`,`_`,`*`,`/`



In [ ]:
## we can add values to a tensor using addition operator
tensor = tf.constant([[7,10],[3,4]])
tensor,
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 20],
       [13, 14]], dtype=int32)>

In [ ]:
## tensor Multiplication
tensor_2 = tf.constant([[5,3,8],
 [3,4,5]])
tensor_2 * 3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[15,  9, 24],
       [ 9, 12, 15]], dtype=int32)>

In [ ]:
## tensor division
tensor_3 = tf.constant([[10,20],
 [30,40]])
tensor_3 / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [ ]:
## tensor substraction
tsubstraction = tf.constant([[9,-2],
 [8,-4]])
tsubstraction - 4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, -6],
       [ 4, -8]], dtype=int32)>

In [ ]:
## tensor builtin operation

tf.math.multiply(tensor,30)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[210, 300],
       [ 90, 120]], dtype=int32)>

In [ ]:
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 3,  4]], dtype=int32)>

Matrix multiplication

In machine learning matrix operation is one of the most common tensor operation

There are two rules our matrix or tensors needs to fulfil if we are going to matrix multiply them.

1. The inner dimention must match.
2. The resulting matrix has the shape of the outer dimention



In [ ]:
## Matrix multiplication in tensor
tensor_2 = tf.constant([[9,12],
 [13,14]])
print(tensor)
tf.linalg.matmul(tensor,tensor_2)

tf.Tensor(
[[ 7 10]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[193, 224],
       [ 79,  92]], dtype=int32)>

In [ ]:
## Matrix multiplication of tensors
tensorm1 = tf.constant([[1,2,1],[0,1,0],[2,3,4]])
tensorm2 = tf.constant([[2,5],[6,7],[1,8]])
tf.matmul(tensorm1,tensorm2)
tensorm1.ndim,tensorm2.ndim
tensorm1.shape,tensorm2.shape


(TensorShape([3, 3]), TensorShape([3, 2]))

In [ ]:
tensorm1 @ tensorm2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
# Create a tensor(3,2)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# Create another tensor of shape (3,2)
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Let us matrix multiply tensors of same shape

tf.matmul(X,Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# Lets change the shape of Y

tf.reshape(Y,shape = (2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Lets try to matrix multiply X with reshaped Y
X@ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(X,shape=(2,3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
## using tf.matmul() for multiplication
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Try change the shape of X instead of Y
tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# we can do the same with transpose
## the difference between transpose and reshape is
# ## The teanspose flips the axises where as reshape shuffels the tensor
# randomly into the shape you want
X, tf.transpose(X) , tf.reshape(X , shape=(2,3))


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# So try matrix multiplication using transpose rather than reshape

tf.matmul(X, tf.transpose(Y)),
tf.matmul(tf.transpose(X),Y)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Dot product.

The matrix multiplication is also reffered to as dot product.
=> We can perform matrix multiplication using.
1. `tf.matmul()`
2. `tf.tensordot()`

In [ ]:
## Performe the dot product on X or Y here we need to transpose the X or Y

tf.tensordot(tf.transpose(X), Y, axes = 1 )


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
##perform the multiplaction using reshape
tf.matmul(tf.reshape(X, shape = (2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
##perform transpose and reshape using Y change.
tf.matmul(X ,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

NameError: name 'tf' is not defined

## Agrigrating the tensors
Agrigating the tensors means  = condensing them from multiple values to a smaller amount of value.


In [ ]:
## by getting the absolute values

S = tf.constant([-7,-10])
S

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
## absolute value is take all the negative number in one tensor and turn them into positive
tf.abs(S)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

**Lets go through the following form of agrigation**

*   Get the minimum
*   Get the maximum
*   Get the mean of a tensor
*   Get the sum of a tensor


In [ ]:
import numpy as np

In [ ]:
# create a random tensor with value between 0 to 100 of size 50

E = tf.constant(np.random.randint(0,100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([50, 49, 73, 64, 65, 66, 89, 47, 92, 46, 47, 93, 19, 88, 93, 97, 47,
       59,  6, 81, 50, 41, 10, 65, 34, 71, 89, 50, 97, 84, 41, 65, 80, 83,
       34, 55, 73, 29, 83, 72, 58, 53,  6,  8, 22,  1, 49, 15, 67, 79])>

In [ ]:
tf.size, E.shape, E.ndim


(<function tensorflow.python.ops.array_ops.size_v2(input, out_type=None, name=None)>,
 TensorShape([50]),
 1)

In [ ]:
# Find the minimum of a tensor
print(tf.reduce_min(E)),
# Find the maximum of a tensor
print(tf.reduce_max(E)),
# Find the mean of a tensor
print(tf.reduce_mean(E)),
#Find the sum of a tensor
print(tf.reduce_sum(E))


tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(97, shape=(), dtype=int64)
tf.Tensor(56, shape=(), dtype=int64)
tf.Tensor(2835, shape=(), dtype=int64)


In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [ ]:
import tensorflow_probability as tfp

In [ ]:
# Finfd the varients of a tensor, we need access to tensor flow probablity
#tfp.stats.variance(E)
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=710.0499877929688>

In [ ]:
# find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.64676284790039>

Find the positional maximum and minimum


In [ ]:
# create a tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
np.argmax(F)

np.int64(42)

In [ ]:
#index of our argmax F
print(F[tf.argmax(F)]),
# Find the max value of F
print(tf.reduce_max(F))

# Check for equality
print(F[tf.argmax(F)] == tf.reduce_max(F))


tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(True, shape=(), dtype=bool)
